# Generated by Django 4.0.1 on 2022-06-29 19:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mac_id', models.CharField(max_length=30)),
                ('humidity', models.IntegerField()),
                ('crnt_time', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='Devices_list',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mac_id', models.CharField(max_length=30)),
                ('assigned_to', models.CharField(max_length=30)),
                ('reg_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('status', models.CharField(max_length=5)),
            ],
        ),
    ]
