# Generated by Django 4.0.4 on 2022-07-02 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('devicesManage', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='device_data',
            old_name='humidity',
            new_name='gas_value',
        ),
    ]
